version: '3.8'

services:
  web:
    image: mathiasestiam/imc-web:latest
    container_name: imc-web
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=imc_db

  db:
    image: mathiasestiam/imc-db:latest
    container_name: imc-db
