version: '3.8'

services:
  web:
    build:
      context: ./app
    container_name: imc-web
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=imc_db

  db:
    build:
      context: ./db
    container_name: imc-db
